config/routes.rb
Rails.application.routes.draw do

  root "wordly#index"

  get "/wordly", to: "wordly#index"
  get "/check_word", to: "check_word#index"

  get "/logout", to: "users#destroy"
  get "/games", to: "games#index"

  resources :users do
    resources :games
  end

  #get "/users", to: "users#index"
  #post "/users", to: "users#create"
  #delete "/users", to: "users#destroy"

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/wordly_controller.rb
class WordlyController < ApplicationController

end

app/helpers/wordly_helper.rb
module WordlyHelper
end

app/views/wordly/_header.html.erb
<nav class="nav">
<%= link_to 'Home', root_path, class: "nav-link" %> 

<%= link_to "Start Game", check_word_path, class:"nav-link"  %>

<%= link_to "Scorecard", games_path, class:"nav-link" %>

<% if session[:user_id].nil? %>
    <%= link_to "Login", users_path, class:"nav-link disabled" %> 
<% elsif %>
    <%= link_to User.find_by(id: session[:user_id])[:username], users_path, class:"nav-link" %> 
<% end %>

<% flash.each do |_, message| %>
    <div class="alert alert-primary" role="alert">
    <small><%= message %></small>
    </div>
<% end %>




</nav>

app/views/wordly/index.html.erb
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Wordly game!</h5>
      <p class="card-text">
        <p style="color:#888;">Do you want to play some super amazing, perfect, incredible WORDLY game?</p>
        <p><%= link_to "Start GAME" , check_word_path %></p>

        <div style="white-space:pre">
    <b>HOW TO PLAY</b>

    Guess the correct word in 6 tries.

    Each guess must be a valid 5 letter word
    with non repeating letters.

    After a guess, the tile colors will change to
    show how close your guess was to the word.


    <span style="background-color:#ddd;"> A </span> - Not in the word in any spot

    <span style="background-color:#fef9cc;"> A </span> - In the word but in the wrong spot

    <span style="background-color:#ccfecf;"> A </span> - in the word and in the correct spot
</div>

<pre>
<br>
<b> Next Puzzle: </b><%= time_till_next_game %>
<br>
</pre>


        </p>
    </div>
</div>